" Vim syntax file
" Language: C Additions
" Date: mer. juil. 17 23:54:10 CEST 2019
" Generated by vim_make_syntaxe_file
" http://www.github.com/glaconbleu/blue_scripts
 
" --- Functions 
 
 
" --- Structures 
 
 
" --- Macros 
 
syn keyword cLibMacro _GCC_WRAP_STDINT_H
syn keyword cLibMacro __STDC_CONSTANT_MACROS
syn keyword cLibMacro __STDC_LIMIT_MACROS
 
" --- Enums 
 
 
" --- Members 
 
 
" --- Variables 
 
 
