" Vim syntax file
" Language: C Additions
" Date: mer. juil. 17 23:54:10 CEST 2019
" Generated by vim_make_syntaxe_file
" http://www.github.com/glaconbleu/blue_scripts
 
" --- Functions 
 
 
" --- Structures 
 
 
" --- Macros 
 
syn keyword cLibMacro _STDALIGN_H
syn keyword cLibMacro __alignas_is_defined
syn keyword cLibMacro __alignof_is_defined
syn keyword cLibMacro alignas
syn keyword cLibMacro alignof
 
" --- Enums 
 
 
" --- Members 
 
 
" --- Variables 
 
 
